annotations:
      beta.screwdriver.cd/restrict-pr: all

jobs:
      main:
            image: node:6
            requires: [~pr, ~commit]
            steps:
                - echo: echo hi
      A:
            image: alpine:3.6
            requires: [main]
            steps:
                - echo: echo parallel
      B:
            image: alpine:3.7
            requires: [main]
            steps:
                - echo: echo parallel
      C:
            image: alpine:edge
            requires: [A, B]
            steps:
                - echo: echo bye
